target 'geoComApp' do
    
    use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Braintree'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Stripe'

end
