
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/rmarathay/geocommerce.git'

use_frameworks!

target 'Geocommerce' do
  target 'GeocommerceTests' do
  end
end
